### ISSUE TITLE
S3 Endpoint

### ISSUE THREAD

**Issue by Isengo1989** [shopwareLabs/SwagMediaS3#12]
What is meant with 'mediaUrl' => 'YOUR_S3_OR_CLOUDFRONT_ENDPOINT' - where to find it or how to set it - I have no clue what this means. Please update the Docu.

**Comment by janbuecker** [comment]
This is meant to be the url to reach your media files. Usually, this is a custom domain or the actual s3 bucket url like `https://your-bucket-name.s3-website.eu-central-1.amazonaws.com/`

**Comment by Isengo1989** [comment]
Thanks @janbuecker - figured it out after a while, but maybe a short description would help.

**Comment by janbuecker** [comment]
I've just updated the readme file to clearify the `mediaUrl` parameter.

Thanks for your feedback @Isengo1989.
