### ISSUE TITLE
Not a plugin?

### ISSUE THREAD

**Issue by EtienneBruines** [shopwareLabs/SwagMediaS3#17]
Just wondering, why isn't this a plugin you can find in the Shopware Store? 

(The MIT License would allow it to be done by anyone, but it wouldn't feel right)

**Comment by mitelg** [comment]
hi @EtienneBruines 
this plugin was intended as an example implementation for extending the media adapter of Shopware. As we don't want so support it officially, you can't find it in the store. Though it gets updates from time to time. 

But feel free to use the latest [release](https://github.com/shopwareLabs/SwagMediaS3/releases/tag/v1.0.2) or extend the code for your needs as you like :blush: :+1: 

best regards from Schöppingen
Michael Telgmann
