### ISSUE TITLE
How to download the plugin?

### ISSUE THREAD

**Issue by jugi92** [shopwareLabs/SwagMediaS3#20]
The ReadMe says: 
Download the plugin from the release page and enable it in shopware.
But I can not find the mentioned release page. 
Would you mind sharing a link?
Thanks in advance

**Comment by mitelg** [comment]
Hey @jugi92 
you can find the releases here: https://github.com/shopwareLabs/SwagMediaS3/releases

**Comment by Hotte512** [comment]
I’m not a pro, but:
Clone the repository and build...

You can also try to download the branch, but than composer install might be required.
And don’t forget editing the foldername...
Swagmedias3-master won’t work.
