### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given

### ISSUE THREAD

**Issue by artdevil-de** [shopwareLabs/SwagMediaS3#22]
Servus,

version 2.0.0 will nicht mit Shopware 5.4.6 zusammen spielen.
Per "composer update" wurde Guzzle version 6.3.3 installiert

php error log nachfolgend

--------------------------
[29-Jul-2018 20:14:58 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /pfad/zum/shop/httpdocs/custom/plugins/SwagMediaS3/vendor/guzzlehttp/guzzle/src/Client.php on line 89 and defined in /pfad/zum/shop/httpdocs/custom/plugins/SwagMediaS3/vendor/guzzlehttp/guzzle/src/Client.php:128
Stack trace:
#0 /pfad/zum/shop/httpdocs/custom/plugins/SwagMediaS3/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('setDefaultOptio...', 'verify', '/var/www/vhosts...')
#1 /pfad/zum/shop/httpdocs/engine/Shopware/Components/HttpClient/GuzzleFactory.php(43): GuzzleHttp\Client->__call('setDefaultOptio...', Array)
#2 /pfad/zum/shop/httpdocs/engine/Shopware/Components/HttpClient/GuzzleHttpClient.php(48): Shopware\Components\HttpClient\GuzzleFactory->createClient(Array)
#3 /pfad/zum/shop/httpdocs/var/cache/production_201807181357/proxies/ShopwareProduction14ca002122cedc8419e1085aec506909b8c098b7ProjectContainer.php(2407): Shopware\Components\HttpClient\GuzzleHttpClient->__construct(Object(Shopware\Components\HttpClient\GuzzleFactory), Array)
#4 /pfad/zum/shop/httpdocs/vendor/symfony/dependency-injection/Container.php(297): ShopwareProduction14ca002122cedc8419e1085aec506909b8c098b7ProjectContainer->getShopwarePlugininstaller_HttpClientService()
#5 /pfad/zum/shop/httpdocs/engine/Shopware/Components/DependencyInjection/Container.php(211): Symfony\Component\DependencyInjection\Container->get('shopware_plugin...', 1)
#6 /pfad/zum/shop/httpdocs/engine/Shopware/Components/DependencyInjection/Container.php(143): Shopware\Components\DependencyInjection\Container->doLoad('shopware_plugin...', 1)
#7 /pfad/zum/shop/httpdocs/var/cache/production_201807181357/proxies/ShopwareProduction14ca002122cedc8419e1085aec506909b8c098b7ProjectContainer.php(2447): Shopware\Components\DependencyInjection\Container->get('shopware_plugin...')
#8 /pfad/zum/shop/httpdocs/vendor/symfony/dependency-injection/Container.php(297): ShopwareProduction14ca002122cedc8419e1085aec506909b8c098b7ProjectContainer->getShopwarePlugininstaller_StoreClientService()
#9 /pfad/zum/shop/httpdocs/engine/Shopware/Components/DependencyInjection/Container.php(211): Symfony\Component\DependencyInjection\Container->get('shopware_plugin...', 1)
#10 /pfad/zum/shop/httpdocs/engine/Shopware/Components/DependencyInjection/Container.php(143): Shopware\Components\DependencyInjection\Container->doLoad('shopware_plugin...', 1)
#11 /pfad/zum/shop/httpdocs/var/cache/production_201807181357/proxies/ShopwareProduction14ca002122cedc8419e1085aec506909b8c098b7ProjectContainer.php(2455): Shopware\Components\DependencyInjection\Container->get('shopware_plugin...')
#12 /pfad/zum/shop/httpdocs/vendor/symfony/dependency-injection/Container.php(297): ShopwareProduction14ca002122cedc8419e1085aec506909b8c098b7ProjectContainer->getShopwarePlugininstaller_SubscriptionServiceService()
#13 /pfad/zum/shop/httpdocs/engine/Shopware/Components/DependencyInjection/Container.php(211): Symfony\Component\DependencyInjection\Container->get('shopware_plugin...', 1)
#14 /pfad/zum/shop/httpdocs/engine/Shopware/Components/DependencyInjection/Container.php(143): Shopware\Components\DependencyInjection\Container->doLoad('shopware_plugin...', 1)
#15 /pfad/zum/shop/httpdocs/engine/Shopware/Plugins/Default/Backend/PluginManager/Controllers/Backend/PluginManager.php(212): Shopware\Components\DependencyInjection\Container->get('shopware_plugin...')
#16 /pfad/zum/shop/httpdocs/engine/Library/Enlight/Controller/Action.php(193): Shopware_Controllers_Backend_PluginManager->getPluginInformationAction()
#17 /pfad/zum/shop/httpdocs/engine/Library/Enlight/Controller/Dispatcher/Default.php(549): Enlight_Controller_Action->dispatch('getPluginInform...')
#18 /pfad/zum/shop/httpdocs/engine/Library/Enlight/Controller/Front.php(222): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
#19 /pfad/zum/shop/httpdocs/engine/Shopware/Kernel.php(215): Enlight_Controller_Front->dispatch()
#20 /pfad/zum/shop/httpdocs/vendor/symfony/http-kernel/HttpCache/HttpCache.php(486): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /pfad/zum/shop/httpdocs/engine/Shopware/Components/HttpCache/AppCache.php(268): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true, NULL)
#22 /pfad/zum/shop/httpdocs/vendor/symfony/http-kernel/HttpCache/HttpCache.php(253): Shopware\Components\HttpCache\AppCache->forward(Object(Symfony\Component\HttpFoundation\Request), true)
#23 /pfad/zum/shop/httpdocs/engine/Shopware/Components/HttpCache/AppCache.php(105): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true)
#24 /pfad/zum/shop/httpdocs/shopware.php(122): Shopware\Components\HttpCache\AppCache->handle(Object(Symfony\Component\HttpFoundation\Request))
#25 {main}
  thrown in /pfad/zum/shop/httpdocs/custom/plugins/SwagMediaS3/vendor/guzzlehttp/guzzle/src/Client.php on line 128

**Comment by shyim** [comment]
Hey,
du musst Guzzle 5 forcen via requirements, dann sollte es funktionieren :)

**Comment by artdevil-de** [comment]
OK, für alle die hier mitlesen,
vor dem
`composer install `

die benötigte Guzzle Version installieren
`composer require guzzlehttp/guzzle:5.3.1`
