### ISSUE TITLE
For easier installation, provide a Release with vendor files installed

### ISSUE THREAD

**Issue by LarsFronius** [shopwareLabs/SwagMediaS3#8]
This would help us until this is an official plugin in order for us to just be able to download the Release package. However, I don't know how this is done generally with shopware, so maybe I just miss a download page here. If so, could you please link me to the right place to get the plugin? Thanks! 👍

**Comment by janbuecker** [comment]
Good catch. I've just implemented a simple build script and released v1.0.0 including the vendor folder :)
